name: Post Merge

on:
  push:
    branches:
      - main

jobs:
  generate:
    name: Sync code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: infracost/setup-opa@v1
      - name: Generate and push
        shell: bash
        run: |
          # Commit any changes and push as needed.
          # See https://github.com/actions/checkout#push-a-commit-using-the-built-in-token
          AUTHOR=gh-pages-updater
          git config user.name ${AUTHOR}
          git config user.email ${AUTHOR}@github.com
          # Prevent looping
          if [[ "$(git log -1 --pretty=format:'%an')" == "${AUTHOR}" ]]; then
              exit 0
          fi
          make
          git add -f policy.wasm
          git commit -sm "policy.wasm: update" || true
          git push origin HEAD:main